### ISSUE TITLE
Request, konfigurasi plugin untuk wordpress dan SID dengan domain yang berbeda

### ISSUE THREAD

**Issue by samsulmaarif** [simasta/wpsid-shortcode#1]
Beberapa website yang saya kelola, wordpress di domain utama (misalnya namadesa.desa.id) dan OpenSID berada di sub domain (misalnya sid.namadesa.desa.id). 

Domain utama RootDirectory-nya terletak di **/home/namadesa/public_html/** sedangkan sub domainnya berada di **/home/namadesa/domains/sid.namadesa.desa.id/public_html/**. 

Bisakah plugin ini digunakan dengan konfigurasi tersebut? Lalu bagaimana jika website (wordpress) dan SID berada di hosting yang berbeda (dengan domain yang berbeda pula tentunya)?

**Comment by simasta** [comment]
ok mas @samsulmaarif, ditampung di versi 1.0.6, 
nanti kita bisa pakai setting > plugin option, untuk path opensid.

**Comment by samsulmaarif** [comment]
Sip, mantap. Pasti akan sangat bermanfaat buat desa-desa yang sudah dan
akan menerapkan SID dan OpenSID.

-- terkirim dari ponsel #linux
@samsulmaarif_

http://www.samsul.web.id | http://www.puskomedia.id

Pada tanggal 12 Apr 2017 7.36 PM, "simasta" <notifications@github.com>
menulis:

**Comment by simasta** [comment]
sudah mas @samsulmaarif , di versi 1.0.6 sudah bisa dicustom.

![screenshot-4](https://cloud.githubusercontent.com/assets/26613576/25168582/4d54f5b0-250e-11e7-9087-33d492f8acd4.jpg)
