### ISSUE TITLE
fitur layanan mandiri wpsid shortcode

### ISSUE THREAD

**Issue by mdwone** [simasta/wpsid-shortcode#2]
hi master sy sangat senang mengunakan apa yang anda buat (plugin wp opensid/sid)
plugin ini sangat membatru dalam penerapan wordpress sebagai website desa. saya harap wpsid-shortcode bisa menambah fitur baru seperti code layanan mandiri 😊

**Comment by simasta** [comment]
ok @mdwone, akan sya coba yach

**Comment by simasta** [comment]
Silahkan dicoba mas @mdwone, saat ini belum saya update di wordpressnya,jadi sementara bisa di download di https://codeload.github.com/simasta/wpsid-shortcode/zip/devel atau menggunakan git melalui commandline git clone https://github.com/simasta/wpsid-shortcode

atau bisa dicek di http://wpsid-shortcode.plugin.demo.siini.com/, tetapi server sedang  error, tidak dapat menyimpan session, jadi tidak bisa login di layanan mandiri

**Comment by mdwone** [comment]
terimakasih. senang rasanya fitur ini sudah tersedia.  setelah saya cek untuk login dengan nik yg salah notifikasi kesalahan tidah muncul. tapi ini sudah bagus👍

**Comment by simasta** [comment]
sekarang sudah diperbaiki, untuk saat ini modelnya memang masih menyamakan dengan opensid, nantinya akan diperbaiki lagi

**Comment by mdwone** [comment]
sepertinya master simasta dapat dengan mudah melakukan ini. 💪 saya suda melihat demo nya. semoga makin banyak fitur yg ditambahkan dan semakin banyak juga yg mengunakan. 😊😊😊😊

**Comment by simasta** [comment]
Ok terima kasih

**Comment by ZulIhwandi** [comment]
mohon bantuan untuk instal wpsid nya para master

**Comment by ayiroger** [comment]
Halo master,sya sudah mencoba mengintegrasikan wpsid source code dan opensid di wordpress. Database connect ok. Tp pas saya tempel source coce wpsid di halaman wordpress terjadi error.adakah solusinya..
