### ISSUE TITLE
Error Data Statistik OpenSID Tidak Tampil

### ISSUE THREAD

**Issue by siayi** [simasta/wpsid-shortcode#4]
Data Statistik OpenSID Tidak Dapat Ditampilkan,
muncul pesan error pada halaman sebagai berikut:
`Fatal error: Call to a member function clean_string() on null in /var/www/html/xxx/opensid/donjo-sys/core/Input.php on line 737`

**Comment by siayi** [comment]
Pesan Error : 
`Fatal error: Call to a member function clean_string() on null in /var/www/html/xxx/opensid/donjo-sys/core/Input.php on line 737`
menjadi tidak ada setelah menambahkan baris kode:
`define('UTF8_ENABLED', FALSE);`
pada file /var/www/html/xxx/wp-config.php

Namun, Data Statistik masih tidak tampil dan keluar pesan error sebagai berikut:
`Fatal error: Call to a member function xss_clean() on null in /var/www/html/xxx/opensid/donjo-sys/core/Input.php on line 699`

**Comment by simasta** [comment]
Silahkan dicoba dengan versi 1.0.9.2 mas @siayi

**Comment by simasta** [comment]
atau bisa test juga melalui http://wpsid-shortcode.plugin.demo.siini.com/
